/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: "autogenerated", dirName: "."}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: "category",
      label: "The Basics",
      link: {type: "generated-index"},
      items: [
        "overview",
        "basic/getting-started",
        "basic/usage",
      ],
    },
    {
      type: "category",
      label: "Build",
      link: {type: "generated-index"},
      items: [
        "build/configuration",
        "build/process",
      ],
    },
    {
      type: "category",
      label: "Configuration and Integration",
      link: {type: "generated-index"},
      items: [
        "configuration/connect-casdoor-server",
        "configuration/import-from-other-authenticators",
      ],
    },
  ],
};
